- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.ram4india.space
  tasks:
  - name: installing mysql packages
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: starting mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: login to mysql
    community.mysql.mysql_info:
     login_host: "{{ login_host }}"
     login_user: root
     login_password: "{{ mysql_root_password }}"
    ignore_errors: true
    register: mysql_info

  - name: printing mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
  
  - name: setting up MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true
